/**
 * LaTeX Generator - Generates LaTeX code from canvas elements
 */
export class LatexGenerator {
    constructor(options = {}) {
        this.posterWidth = options.posterWidth || 841;  // mm
        this.posterHeight = options.posterHeight || 1189; // mm
    }

    /**
     * Update poster dimensions
     */
    setPosterSize(width, height) {
        this.posterWidth = width;
        this.posterHeight = height;
    }

    /**
     * Generate complete LaTeX document
     * @param {BaseElement[]} elements
     * @returns {string}
     */
    generate(elements) {
        const preamble = this.generatePreamble();
        const content = this.generateContent(elements);
        const closing = this.generateClosing();

        return `${preamble}\n\n${content}\n\n${closing}`;
    }

    /**
     * Generate LaTeX preamble
     */
    generatePreamble() {
        const widthCm = (this.posterWidth / 10).toFixed(1);
        const heightCm = (this.posterHeight / 10).toFixed(1);

        return `% ============================================
% LaTeX Poster - Generated by LaTeX Poster Editor
% Compile with: pdflatex or xelatex
% ============================================

\\documentclass{article}

% Page setup
\\usepackage[paperwidth=${widthCm}cm, paperheight=${heightCm}cm, margin=0pt]{geometry}

% Required packages
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{mathptmx}           % Times New Roman font (for \\rmfamily)
\\usepackage{helvet}             % Helvetica/Arial font (for \\sffamily)
\\usepackage{courier}            % Courier font (for \\ttfamily)
\\usepackage{graphicx}           % For images and rotatebox
\\usepackage{xcolor}             % For colors
\\usepackage[absolute,overlay]{textpos}  % For absolute positioning
\\usepackage{tikz}               % For shapes and drawings

% textpos configuration - origin at top-left, units in cm
\\setlength{\\TPHorizModule}{1cm}
\\setlength{\\TPVertModule}{1cm}
\\textblockorigin{0cm}{0cm}

% Remove page number
\\pagestyle{empty}

\\begin{document}

% TikZ layer for shapes - uses page.north west as origin
% Environments will be created as needed`;
    }

    /**
     * Generate content from elements
     */
    generateContent(elements) {
        if (!elements || elements.length === 0) {
            return '% No elements added yet';
        }

        let content = '';
        elements.forEach(el => {
            content += '\n' + el.toLatex() + '\n';
        });

        return content;
    }

    /**
     * Generate document closing
     */
    generateClosing() {
        return `\\end{document}`;
    }

    /**
     * Generate a minimal example for quick testing
     */
    generateMinimalExample() {
        return `% Minimal LaTeX Poster Example
\\documentclass{article}
\\usepackage[paperwidth=84.1cm, paperheight=118.9cm, margin=0pt]{geometry}
\\usepackage{graphicx}
\\usepackage{xcolor}
\\usepackage[absolute,overlay]{textpos}

\\setlength{\\TPHorizModule}{1cm}
\\setlength{\\TPVertModule}{1cm}
\\textblockorigin{0cm}{0cm}
\\pagestyle{empty}

\\begin{document}

% Example text block
\\begin{textblock}{20}(5,5)
  {\\fontsize{48pt}{58pt}\\selectfont\\bfseries
  Hello World!}
\\end{textblock}

\\end{document}`;
    }
}
